name: english_trainer
description: Offline English grammar & vocabulary trainer (Android, Windows, Linux).
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_markdown: ^0.7.4
  markdown: ^7.3.1
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#2F80ED"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"

flutter:
  uses-material-design: true
  assets:
    - assets/content.json
    - assets/parts_ru.json
    - assets/words.json
    - assets/examples_ru.json
    - assets/definitions_ru.json
    - assets/ipa.json
    - assets/irregular_verbs.json
